name       : mate-tweak
version    : 21.10.0
release    : 20
source     :
    - https://github.com/ubuntu-mate/mate-tweak/archive/21.10.0.tar.gz : 1bacc9b92960c712697e0c44fbcaaebed9683b4ff899af5af88506f7e13e1aff
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Tweak tool for the MATE Desktop
description: |
    Tweak tool for the MATE Desktop
builddeps  :
    - pkgconfig(python3)
    - python-distutils-extra
rundeps    :
    - ccsm
    - python-distro
    - python-gobject
    - python-psutil
    - python-setproctitle
build      : |
    %python3_setup
install    : |
    %python3_install
