name       : mate-tweak
version    : 17.04.1
release    : 3
source     :
    - https://bitbucket.org/ubuntu-mate/mate-tweak/get/17.04.1.tar.gz : 5b1ad14287a636ead462de53d595871040bdd56649b431b545d2a4ba9d14cf70
license    : GPL-2.0
component  : desktop.mate
summary    : Tweak tool for the MATE Desktop
description: |
    Tweak tool for the MATE Desktop
builddeps  :
    - pkgconfig(python-3.5)
    - python-distutils-extra
rundeps    :
    - python3-gobject
    - python-psutil
    - python-setproctitle
build      : |
    %python3_setup
install    : |
    %python3_install
