name       : mate-tweak
version    : 19.10.4
release    : 16
source     :
    - https://github.com/ubuntu-mate/mate-tweak/archive/19.10.4.tar.gz : e4c3d75ce247ab9724ecbfbb3292dbadd523b01e06d435303f6da3af88b172a5
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Tweak tool for the MATE Desktop
description: |
    Tweak tool for the MATE Desktop
builddeps  :
    - pkgconfig(python3)
    - python-distutils-extra
rundeps    :
    - ccsm
    - python3-gobject
    - python-distro
    - python-psutil
    - python-setproctitle
build      : |
    %python3_setup
install    : |
    %python3_install
