name       : mate-tweak
version    : 17.10.15
release    : 8
source     :
    - https://github.com/ubuntu-mate/mate-tweak/archive/17.10.15.tar.gz : 1bcd01bfd3882cf01c20347649afcec721edab5473af1568a33e880d305322db
license    : GPL-2.0
component  : desktop.mate
summary    : Tweak tool for the MATE Desktop
description: |
    Tweak tool for the MATE Desktop
builddeps  :
    - pkgconfig(python3)
    - python-distutils-extra
rundeps    :
    - python3-gobject
    - python-psutil
    - python-setproctitle
build      : |
    %python3_setup
install    : |
    %python3_install
