name       : mate-tweak
version    : 18.10.2
release    : 13
source     :
    - https://github.com/ubuntu-mate/mate-tweak/archive/18.10.2.tar.gz : 1e5eea75339c1e45f3d643f7c0750fac1e1814958b1dd3f846f7a49faf1fabfb
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Tweak tool for the MATE Desktop
description: |
    Tweak tool for the MATE Desktop
builddeps  :
    - pkgconfig(python3)
    - python-distutils-extra
rundeps    :
    - python3-gobject
    - python-psutil
    - python-setproctitle
build      : |
    %python3_setup
install    : |
    %python3_install
