name       : mate-tweak
version    : 3.5.10.1
release    : 1
source     :
    - https://bitbucket.org/ubuntu-mate/mate-tweak/get/3.5.10.1.tar.bz2 : d660207951a7dc36f480699f06b7c0e504e79d49ebe4f73f09540c57fc4a2bce
license    : GPL-2.0
component  : desktop.mate
summary    : Tweak tool for the MATE Desktop
description: |
    Tweak tool for the MATE Desktop
builddeps  :
    - pkgconfig(python-3.5)
    - python-distutils-extra
rundeps    :
    - python3-gobject
    - python-psutil
build      : |
    %python3_setup    
install    : |
    %python3_install
