name       : mate-tweak
version    : 18.04.8
release    : 9
source     :
    - https://github.com/ubuntu-mate/mate-tweak/archive/18.04.8.tar.gz : bb42e00b9b0ae7612b99efe63a4d7aea925cd361a588fbc19c477e87cd3a2472
license    : GPL-2.0
component  : desktop.mate
summary    : Tweak tool for the MATE Desktop
description: |
    Tweak tool for the MATE Desktop
builddeps  :
    - pkgconfig(python3)
    - python-distutils-extra
rundeps    :
    - python3-gobject
    - python-psutil
    - python-setproctitle
build      : |
    %python3_setup
install    : |
    %python3_install
