name       : mate-tweak
version    : 22.04.2
release    : 22
source     :
    - https://github.com/ubuntu-mate/mate-tweak/archive/refs/tags/22.04.2.tar.gz : 68d922c62159d022be748b0eb587b1d742f1c9f4bd721b9208153d5486f17350
license    : GPL-2.0-or-later
component  : desktop.mate
summary    : Tweak tool for the MATE Desktop
description: |
    Tweak tool for the MATE Desktop
builddeps  :
    - pkgconfig(python3)
    - python-distutils-extra
rundeps    :
    - ccsm
    - python-distro
    - python-gobject
    - python-psutil
    - python-setproctitle
build      : |
    %python3_setup
install    : |
    %python3_install
