name       : mate-tweak
version    : 18.04.9
release    : 11
source     :
    - https://github.com/ubuntu-mate/mate-tweak/archive/18.04.9.tar.gz : 52d67bb8b52b08a1027677ee671da507977d2db299d40c77eb164c8419e529ae
license    : GPL-2.0
component  : desktop.mate
summary    : Tweak tool for the MATE Desktop
description: |
    Tweak tool for the MATE Desktop
builddeps  :
    - pkgconfig(python3)
    - python-distutils-extra
rundeps    :
    - python3-gobject
    - python-psutil
    - python-setproctitle
setup      : |
    %apply_patches
build      : |
    %python3_setup
install    : |
    %python3_install
